name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install @semantic-release/git @semantic-release/changelog
      
      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
          required_pull_request_reviews: |
            null
          required_status_checks: |
            null
          enforce_admins: |
            null
          restrictions: | 
            null 
        env:
          GITHUB_TOKEN: ${{ secrets.ALLOW_MERGE }}
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ALLOW_MERGE }}
        run: npx semantic-release

      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/main/protection
          repository: ${{ github.repository }}
          required_pull_request_reviews: |
            required_approving_review_count: 1       
          required_status_checks: |
            null
          enforce_admins: |
              null
          restrictions: | 
              null
        env:
          GITHUB_TOKEN: ${{ secrets.ALLOW_MERGE }}
